# Generated by Django 4.2.9 on 2026-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255, verbose_name='Cible (IP/Hôte)')),
                ('ports', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ports')),
                ('mode', models.CharField(choices=[('Rapide', 'Rapide'), ('Complet', 'Complet'), ('Personnalisé', 'Personnalisé')], max_length=20, verbose_name='Mode de scan')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='Résultats')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
            ],
            options={
                'verbose_name': 'Historique de scan',
                'verbose_name_plural': 'Historiques de scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
